//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }
            [DisplayName("Mã đơn hàng")]
        public int MaDonHang { get; set; }
        [DisplayName("Đã thanh toán")]
        public Nullable<int> DaThanhToan { get; set; }
        [DisplayName("Tình trạng giao hàng")]
        public Nullable<int> TinhTrangGiaoHang { get; set; }
        [DisplayName("Ngày đặt")]
        public Nullable<System.DateTime> NgayDat { get; set; }
        [DisplayName("Ngày giao")]
        public Nullable<System.DateTime> NgayGiao { get; set; }
        [DisplayName("Mã Khách Hàng")]
        public Nullable<int> MaKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
