//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NhaXuatBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaXuatBan()
        {
            this.SAches = new HashSet<SAch>();
        }
    
        public int MaNXB { get; set; }

        [Display(Name = "Tên nhà xuất bản: ")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string TenNXB { get; set; }

        [Display(Name = "Địa chỉ: ")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        public string DiaChi { get; set; }

        [Display(Name = "Số điện thoại: ")]
        [Required(ErrorMessage = "{0} không được để trống!")]
        [Phone(ErrorMessage = "Xin hãy nhập số điện thoại!")]
        [MinLength(9, ErrorMessage = "Xin hãy nhập đủ số điện thoại!")]
        [MaxLength(11, ErrorMessage = "Không quá 11 số!")]
        public string DienThoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAch> SAches { get; set; }
    }
}
