//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.RegularExpressions;

namespace BookStore.Models
{
    public class TrungTK
    {
        [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
        public sealed class TrungTKs : ValidationAttribute
        {
            protected override ValidationResult IsValid(object value, ValidationContext validationContext)
            {
                QLBanSachEntities5 db = new QLBanSachEntities5();
                List<KhachHang> lstKH = db.KhachHangs.ToList();
                if (value != null)
                {
                    var test = Convert.ToString(value);
                    foreach(var item in lstKH)
                    {
                        if (String.Compare(test,item.TaiKhoan,true) == 0)
                            return new ValidationResult("Tên tài khoản này đã có người sử dụng!");
                   
                    }

                }
                return ValidationResult.Success;
            }
        }
    }
}