//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace BookStore.Models
{
    public class UserCustomValidation
    {
        [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
        public sealed class ValidBirthDate : ValidationAttribute
        {
            protected override ValidationResult IsValid(object value, ValidationContext validationContext)
            {
                
                
                if (value != null)
                {
                    DateTime _birthJoin = Convert.ToDateTime(value);
                    
                    if(_birthJoin < DateTime.Now.AddYears(-100))
                    {
                        return new ValidationResult("Ngày tháng năm sinh không thể bé hơn " + DateTime.Now.AddYears(-100).Date);
                    }
                    if(_birthJoin > DateTime.Now.AddYears(-10))
                    {
                        return new ValidationResult("Người dùng phải trên 10 tuổi!");
                    }
                }
                return ValidationResult.Success;
            }
        }
    }
}